//! `serve` subcommand — MCP server (stdio JSON-RPC 2.0) via rmcp 1.7.0.
//!
//! P010 shipped handshake only. P011 wires 6 tools via `AdvisoryInboxService`
//! (parse_report, dedup, append, migrate_state, state_backfill, scan_and_append)
//! per ARCHITECTURE.md §6.
//!
//! Architecture decisions (P010 preserved, P011 extended):
//! - Transport wiring (stdio) stays in this file; `src/mcp/` owns tool logic.
//! - tokio current_thread runtime built INSIDE this fn (no `#[tokio::main]` in main.rs).
//! - `ServerCapabilities` with tools enabled — generated by `#[tool_router(server_handler)]`.

use anyhow::{Context, Result};
use rmcp::{ServiceExt, transport::io::stdio};

use crate::mcp::tools::AdvisoryInboxService;

pub fn run() -> Result<()> {
    // Optional verbose flag from env (debug aid).
    let verbose = std::env::var("ADVISORY_INBOX_VERBOSE").unwrap_or_default();
    if !verbose.is_empty() {
        eprintln!("[serve] verbose={verbose}");
    }

    // Build current-thread runtime (Cargo.toml declares `rt` feature only — NO multi-thread).
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .context("building tokio current_thread runtime for MCP serve")?;

    runtime.block_on(async {
        let server = AdvisoryInboxService;
        let transport = stdio();
        let running = server
            .serve(transport)
            .await
            .context("initializing MCP server handshake")?;
        running
            .waiting()
            .await
            .context("MCP server transport runtime")?;
        Ok::<(), anyhow::Error>(())
    })?;

    Ok(())
}
